version: '3'

services:
  api:
    # caminho do dockerfile
    build: .
    ports:
      - "4000:4000"
    environment:
      PRISMA_ENDPOINT: http://prisma:4466
    command: yarn start
    expose:
      - "4000"

  prisma:
    image: prismagraphql/prisma:1.28
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            schema: public
            host: db
            database: finances
            port: 5432
            user: admin
            password: admin
            migrations: true

  db:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "2345:5432"

volumes:
  postgres:
